const ACTIONS = {
    UPDATE_MESSAGE : 'UPDATE_MESSAGE',
    UPDATE_BOARD : "UPDATE_BOARD",
    SIGNIN : 'SIGNIN',
    WINNER : 'WINNER',
    FULL_RESET : "FULL_RESET",
    REPLAY : 'REPLAY',
    TIE : 'TIE'
}


export default ACTIONS